---
kind: pipeline
type: exec
name: default

trigger:
  ref:
    - refs/heads/master # All pushes to master

    - refs/heads/drone # All pushes to yarn

    - refs/pull/*/* # All pull requests regardless of branch

    - refs/tags/* # Tags for releasing/etc

platform:
  os: linux
  arch: amd64

workspace:
  base: /node

steps:
  - name: greeting
    commands:
      - echo hello world
      - curl -fsSL https://github.com/github/hub/raw/master/script/get | bash -s 2.14.1
      - echo "done"
